M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu22.04.1} date 2024-11-26T13:49:19+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-26T13:49:19+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X0.2202Y0.8676
X0.2202Y0.6401
M30
