M48
; DRILL file {KiCad 8.0.7-8.0.7-0~ubuntu22.04.1} date 2024-12-28T00:36:34+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-28T00:36:34+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7-8.0.7-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
%
G90
G05
T1
X0.2372Y0.8494
X0.2372Y0.6218
M30
