M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu22.04.1} date 2024-11-26T13:48:23+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-26T13:48:23+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0492
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0591
%
G90
G05
T1
X1.5494Y1.038
X1.8635Y1.038
T2
X0.1624Y0.491
X0.438Y0.491
M30
